version: '3.3'

services:
  backend:
    build: .
#    command: sh ./commands.sh
    command:
      - sh
      - -c
      - |
        python manage.py makemigrations backend --noinput
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - postgres
#      - db
    expose:
      - 8000
#  db:
#    image: busybox
#    volumes:
#      - ./data:/data/db
  postgres:
    image: 'postgres'
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_DB=netology
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs:/var/logs
    restart: unless-stopped

  nginx:
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80

volumes:
  postgres_data:
  static_volume:
  media_volume: